language: go

os:
  - linux
  - osx

arch:
  - amd64
  - arm64
  - x86

go:
  - 1.13

addons:
  apt:
    update: true

install:
  - sudo apt-get -y install upx

before_script:
  - go mod tidy

script:
  - buildTime=$(date +'%Y-%m-%d_%T')
  - gitSHA=$(git rev-parse HEAD)
  - cd cmd/dockohealer
  - go build -ldflags "-X main.buildTime=$buildTime -X main.gitSHA=$gitSHA -X main.versionStrings=$TRAVIS_TAG"
  - ./dockohealer -version

after_success:
  - if [ "$TRAVIS_TAG" != "" ]; then upx --brute dockohealer; fi

before_deploy:
  - if [ "$TRAVIS_TAG" != "" ]; then mv dockohealer dockohealer-$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH-$TRAVIS_TAG; fi

deploy:
  provider: releases
  user: maateen
  password: $GITHUB_TOKEN
  file: dockohealer-$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH-$TRAVIS_TAG
  overwrite: true
  on:
    tags: true